name: SwordofMagic7-Core
version: '${project.version}'
main: com.somrpg.swordofmagic7.Core.SomCore
api-version: 1.18
authors: [ MomiNeko ]

commands:
  somreload:
    permission: som7.developer
    description: description
    usage: /<command>
  save:
    permission: som7.developer
    description: description
    usage: /<command>
  load:
    permission: som7.developer
    description: description
    usage: /<command>


  getItem:
    permission: som7.admin
    description: description
    usage: /<command>
  getRune:
    permission: som7.admin
    description: description
    usage: /<command>


  gm:
    permission: som7.builder
    description: description
    usage: /<command>
  playmode:
    permission: som7.builder
    aliases: pm
    description: description
    usage: /<command>


  menu:
    aliases: m
    description: description
    usage: /<command>
  settingMenu:
    aliases: [setting, sm]
    description: description
    usage: /<command>
  damageLog:
    description: description
    usage: /<command>
  expLog:
    description: description
    usage: /<command>
  dropLog:
    description: description
    usage: /<command>
  castMode:
    description: description
    usage: /<command>
  strafeMode:
    description: description
    usage: /<command>
  pvpMode:
    description: description
    usage: /<command>
  userMenuType:
    description: description
    usage: /<command>